(function () {
  window.STARKSON_DEPARTMENTS = [
    'PRODUCTION', 'PRINTING', 'ENGINEERING', 'WAREHOUSE', 'SUPPLY CHAIN ACCOUNTING',
    'HUMAN RESOURCES', 'LOGISTICS', 'ACCOUNT RELATIONSHIP', 'PPIC WAREHOUSE',
    'QUALITY ASSURANCE', 'TECHNICAL SERVICE', 'INFORMATION TECHNOLOGY',
    'PRODUCTION PLANNING AND INVENTORY CONTROL', 'PRODUCTION/WAREHOUSE',
    'INDUSTRIAL ENGINEERING', 'MAINTENANCE', 'WAREHOUSE AND LOGISTICS',
    'BUSINESS DEVELOPMENT', 'TECHNICAL SERVICES', 'PPIC FLEXIBLES',
    'MANUFACTURING', 'R&D', 'QMC'
  ];
})();